locale: "en-US"
site_theme: "default"
title: "Junteng Liu"
name: "Junteng Liu"
description: "Junteng Liu's academic portfolio"
url: "https://toolathlon68-arch.github.io"
baseurl: "/LJT-Homepage"
repository: "toolathlon68-arch/LJT-Homepage"

author:
  avatar: ""
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group"
  employer: "Hong Kong University of Science and Technology"
  email: "jliugi@connect.ust.hk"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

publication_category:
  manuscripts:
    title: "ArXiv Preprints"
  conferences:
    title: "Conference Papers"

breadcrumbs: false
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: false
atom_feed:
  hide: true

include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  publications:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
